### ISSUE TITLE
Invalid document type, expecting: truthy

### ISSUE THREAD

**Issue by haovn577** [pelias/geonames#28]
I tried to import by command:  ./bin/pelias-onames -i nz, but got the below error:
Also, try to get last updated pelias-model (3.10.1) but still this error.
[Node v0.10.25, Npm 1.3.10, Ubuntu 14.04]
```
Exception: PeliasModelError: invalid document type, expecting: truthy, got: 
    at /home/hao/working/pelias/geonames/node_modules/pelias-model/util/valid.js:31:13
    at /home/hao/working/pelias/geonames/node_modules/pelias-model/util/model.js:331:7
    at Array.forEach (native)
    at validate (/home/hao/working/pelias/geonames/node_modules/pelias-model/util/model.js:330:16)
    at Document.setter [as setSourceId] (/home/hao/working/pelias/geonames/node_modules/pelias-model/util/model.js:50:5)
    at new Document (/home/hao/working/pelias/geonames/node_modules/pelias-model/Document.js:27:8)
    at DestroyableTransform.mapper [as _transform] (/home/hao/working/pelias/geonames/task/import.js:15:14)
    at DestroyableTransform.Transform._read (/home/hao/working/pelias/geonames/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/hao/working/pelias/geonames/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/hao/working/pelias/geonames/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/hao/working/pelias/geonames/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/home/hao/working/pelias/geonames/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (_stream_readable.js:583:24)
```
Br,
Hao Tran

**Comment by orangejulius** [comment]
Hey @haovn577,
I just tried a geonames import with the same node version and country, and things seemed to work. Here's a printout of my Node version, NPM version, and `npm list`. If you see any big differences let me know, and hopefully I can help you debug further.


[output.txt](https://github.com/pelias/geonames/files/110023/output.txt)

**Comment by orangejulius** [comment]
Hey @haovn577,
It's been a while, so hopefully we've fixed everything here, and I'm going to close this issue. If you're still experiencing problems, please let us know here, or in another issue.
